### ISSUE TITLE
Project (Domain) Name

### ISSUE THREAD

**Issue by austinpray** [UTD-CRSS/exploreapollo.org-project-documentation#2]
Let's start thinking of what we want to name this project so we can buy some domains and such.

I'll start:
- exploreapollo.org
- apolloaudio.org

Any ideas? I would rather lean more toward the "generic" exploreapollo.org so we don't put ourselves in a corner.

**Comment by nicolemon** [comment]
I like exploreapollo. Other suggestions:
- listenapollo
- aupollo (weak portmanteau of audio and apollo, makes me think of chicken and polio, is a terrible idea)

**Comment by JamieCrisman** [comment]
audio(11?)mission

**Comment by austinpray** [comment]
@UTD-CRSS/apollo so going to lock in "exploreapollo.org" as the domain for the project. All good?

**Comment by nicolemon** [comment]
![](http://www.exoticanimalsforsale.net/img/aye-aye2.jpg), 

![](http://redcrosschat.org/wp-content/uploads/2013/06/captain-crunch-face.gif)

**Comment by austinpray** [comment]
Let's go with "Explore Apollo" aka "exploreapollo.org"
